"""initial schema: 12 tables

Revision ID: 979bae82fe9e
Revises: 
Create Date: 2026-07-18 01:26:13.191117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '979bae82fe9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('IO', 'SHO', 'LEGAL_ADVISOR', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('case_type', sa.Enum('CONVENTIONAL', 'CYBER_FINANCIAL', name='casetype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('fir_number', sa.String(), nullable=True),
    sa.Column('fir_date', sa.Date(), nullable=True),
    sa.Column('police_station', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('COMPLAINT', 'INVESTIGATION', 'ARREST', 'REMAND', 'CHARGESHEET', name='casestatus'), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_location', sa.String(), nullable=True),
    sa.Column('complaint_narrative', sa.Text(), nullable=True),
    sa.Column('complaint_language', sa.Enum('GU', 'HI', 'EN', name='language'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('field_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('PANCHNAMA', 'REMAND', 'SEIZURE_RECEIPT', 'MEDICAL_LETTER', 'CUSTODY_LETTER', 'FACE_ID', 'CHARGESHEET', 'LERS_REQUEST', name='doctype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('generated_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.Enum('GU', 'HI', 'EN', name='language'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', name='docstatus'), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('act', sa.Enum('BNS', 'BNSS', 'BSA', 'IT_ACT', 'OTHER', name='legalact'), nullable=False),
    sa.Column('section_code', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('triggering_phrase', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ingredient_evidence_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUGGESTED', 'ACCEPTED', 'REJECTED', name='sectionstatus'), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('VICTIM', 'ACCUSED', 'WITNESS', 'COMPLAINANT', name='personrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'DOCUMENT', 'PHYSICAL', name='evidencetype'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_person_id', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('chain_of_custody', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seized_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seized_from', sa.Integer(), nullable=True),
    sa.Column('seizure_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seizure_location', sa.String(), nullable=True),
    sa.Column('item_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['seized_from'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.Enum('WITNESS', 'ACCUSED', 'VICTIM', name='statementtype'), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('GU', 'HI', 'EN', name='language'), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_type', sa.Enum('COMPLAINT', 'WITNESS_EXAM', 'EVIDENCE_SEIZURE', 'ARREST', 'REMAND', 'DOC_GENERATED', 'OTHER', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.Column('related_evidence_id', sa.Integer(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_diary_entries')
    op.drop_table('statements')
    op.drop_table('seized_items')
    op.drop_table('evidence')
    op.drop_table('document_versions')
    op.drop_table('persons')
    op.drop_table('legal_sections')
    op.drop_table('judgments')
    op.drop_table('documents')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
