"""Generate the 4 CrimeGPT .docx templates (docxtpl / Jinja placeholders).

Binary .docx are committed, but this script is the reproducible source of truth.
Run from the repo root (or anywhere):  python templates/_build_templates.py

Placeholders use docxtpl syntax:
  {{ field }}                      scalar merge field
  {%tr for x in list %} … {%tr endfor %}   table-row loop (3-row pattern:
        a for-row and endfor-row that docxtpl deletes, wrapping the content row)
"""
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

HERE = Path(__file__).resolve().parent


def _title(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(text)
    r.bold = True
    r.font.size = Pt(14)
    return p


def _line(doc, text, bold=False):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    return p


def _looped_table(doc, headers, for_expr, content_cells, endfor="{%tr endfor %}"):
    """Build a table whose single content row repeats via docxtpl {%tr%}.

    Rows: [header] [for-tag] [content] [endfor-tag]. docxtpl removes the for/endfor
    rows and repeats the content row for each item.
    """
    n = len(headers)
    table = doc.add_table(rows=4, cols=n)
    table.style = "Table Grid"
    for i, h in enumerate(headers):
        table.rows[0].cells[i].text = h
        for r in table.rows[0].cells[i].paragraphs[0].runs:
            r.bold = True
    # for-row: tag in first cell, rest blank (docxtpl drops the whole row)
    table.rows[1].cells[0].text = for_expr
    # content-row: the repeated cells
    for i, c in enumerate(content_cells):
        table.rows[2].cells[i].text = c
    # endfor-row
    table.rows[3].cells[0].text = endfor
    return table


def _sig_block(doc, left_label, right_label):
    doc.add_paragraph()
    t = doc.add_table(rows=1, cols=2)
    t.rows[0].cells[0].text = left_label
    t.rows[0].cells[1].text = right_label
    t.rows[0].cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT


# --------------------------------------------------------------------------
def build_seizure_receipt():
    doc = Document()
    _title(doc, "SEIZURE RECEIPT / જપ્તી પહોંચ")
    _line(doc, "(Under the Bharatiya Nagarik Suraksha Sanhita, 2023)")
    doc.add_paragraph()
    _line(doc, "Police Station: {{ police_station }}    District: {{ district }}")
    _line(doc, "Case / FIR No.: {{ case_number }}  (FIR No. {{ fir_number }})")
    _line(doc, "Date & time of seizure: {{ seizure_datetime }}")
    _line(doc, "Place of seizure: {{ seizure_location }}")
    doc.add_paragraph()
    _line(
        doc,
        "The following article(s) were seized by {{ io_name }}, Investigating Officer, "
        "from the possession of {{ accused_name }} in connection with the above case, "
        "in the presence of the panch witnesses named below:",
    )
    _looped_table(
        doc,
        ["No.", "Description of article", "Quantity", "Estimated value (Rs.)"],
        "{%tr for item in seized_items %}",
        ["{{ loop.index }}", "{{ item.description }}", "{{ item.quantity }}", "{{ item.estimated_value }}"],
    )
    doc.add_paragraph()
    _line(doc, "Panch witnesses:", bold=True)
    _looped_table(
        doc,
        ["No.", "Name", "Address"],
        "{%tr for w in witnesses %}",
        ["{{ loop.index }}", "{{ w.full_name }}", "{{ w.address }}"],
    )
    doc.add_paragraph()
    _line(doc, "The above articles have been correctly listed and seized in my presence.")
    _sig_block(doc, "Panch witnesses (sign)", "{{ io_name }}\nInvestigating Officer")
    _line(doc, "NOTE: Draft generated by CrimeGPT — to be verified and signed by the officer.")
    doc.save(HERE / "seizure_receipt.docx")


def build_panchnama():
    doc = Document()
    _title(doc, "PANCHNAMA / પંચનામું")
    doc.add_paragraph()
    _line(doc, "Police Station: {{ police_station }}    District: {{ district }}")
    _line(doc, "Case / FIR No.: {{ case_number }}  (FIR No. {{ fir_number }})")
    _line(doc, "Date: {{ panchnama_date }}    Place: {{ panchnama_place }}")
    doc.add_paragraph()
    _line(
        doc,
        "Before me, {{ io_name }}, Investigating Officer of the above case, the panch "
        "witnesses named below were called and the purpose of this panchnama was explained "
        "to them. In their presence the following proceedings were carried out:",
    )
    _line(doc, "Panch witnesses:", bold=True)
    _looped_table(
        doc,
        ["No.", "Name", "Father's name", "Address"],
        "{%tr for w in witnesses %}",
        ["{{ loop.index }}", "{{ w.full_name }}", "{{ w.father_name }}", "{{ w.address }}"],
    )
    doc.add_paragraph()
    _line(doc, "Accused:", bold=True)
    _line(
        doc,
        "{{ accused_name }}, son of {{ accused_father }}, age {{ accused_age }}, "
        "residing at {{ accused_address }}.",
    )
    doc.add_paragraph()
    _line(doc, "Narrative of proceedings:", bold=True)
    _line(doc, "{{ proceedings_narrative }}")
    doc.add_paragraph()
    _line(doc, "Articles found / seized during the proceedings:", bold=True)
    _looped_table(
        doc,
        ["No.", "Description", "Quantity", "Estimated value (Rs.)"],
        "{%tr for item in seized_items %}",
        ["{{ loop.index }}", "{{ item.description }}", "{{ item.quantity }}", "{{ item.estimated_value }}"],
    )
    doc.add_paragraph()
    _line(
        doc,
        "The above panchnama was read over and explained to the panchas, who admitted it "
        "to be correct and signed below.",
    )
    _sig_block(doc, "Panch witnesses (sign)", "{{ io_name }}\nInvestigating Officer")
    _line(doc, "NOTE: Draft generated by CrimeGPT — to be verified and signed by the officer.")
    doc.save(HERE / "panchnama.docx")


def build_remand_request():
    doc = Document()
    _line(doc, "To,")
    _line(doc, "The Hon'ble Court of the Learned Judicial Magistrate,")
    _line(doc, "{{ district }}.")
    doc.add_paragraph()
    _title(doc, "APPLICATION FOR POLICE CUSTODY REMAND")
    _line(doc, "(Under Section 187 of the Bharatiya Nagarik Suraksha Sanhita, 2023)")
    doc.add_paragraph()
    _line(doc, "Police Station: {{ police_station }}    District: {{ district }}")
    _line(doc, "Case / FIR No.: {{ case_number }}  (FIR No. {{ fir_number }} dated {{ fir_date }})")
    doc.add_paragraph()
    _line(doc, "Respectfully showeth:", bold=True)
    _line(
        doc,
        "1. That the accused {{ accused_name }}, son of {{ accused_father }}, age "
        "{{ accused_age }}, residing at {{ accused_address }}, has been arrested in "
        "connection with the above case.",
    )
    _line(doc, "2. That the following sections of law have been applied in this case:")
    _looped_table(
        doc,
        ["Act", "Section", "Title"],
        "{%tr for s in sections_applied %}",
        ["{{ s.act }}", "{{ s.section_code }}", "{{ s.section_title }}"],
    )
    _line(doc, "3. Investigation carried out so far:")
    _line(doc, "{{ investigation_done }}")
    _line(doc, "4. Investigation still pending:")
    _line(doc, "{{ pending_investigation }}")
    _line(doc, "5. Grounds for seeking police custody:")
    _line(doc, "{{ grounds_for_custody }}")
    doc.add_paragraph()
    _line(
        doc,
        "It is therefore prayed that the accused be remanded to police custody to enable "
        "completion of the investigation.",
    )
    _sig_block(doc, "Place: {{ police_station }}", "{{ io_name }}\nInvestigating Officer")
    _line(doc, "NOTE: Draft generated by CrimeGPT — to be verified and signed by the officer.")
    doc.save(HERE / "remand_request.docx")


def build_medical_letter():
    doc = Document()
    _line(doc, "To,")
    _line(doc, "The Medical Officer,")
    _line(doc, "{{ hospital }}.")
    doc.add_paragraph()
    _title(doc, "REQUEST FOR MEDICAL EXAMINATION")
    doc.add_paragraph()
    _line(doc, "From: {{ io_name }}, Investigating Officer, {{ police_station }}, {{ district }}.")
    _line(doc, "Case / FIR No.: {{ case_number }}  (FIR No. {{ fir_number }})")
    doc.add_paragraph()
    _line(doc, "Sir / Madam,")
    _line(
        doc,
        "In connection with the above case, {{ subject_name }} ({{ subject_role }}) is being "
        "produced before you. You are requested to conduct the medical examination of the said "
        "person for the following purpose:",
    )
    _line(doc, "Purpose of examination: {{ examination_purpose }}")
    doc.add_paragraph()
    _line(
        doc,
        "You are further requested to furnish the medical examination report and certificate "
        "to this office at the earliest for the purpose of investigation.",
    )
    _sig_block(doc, "Place: {{ police_station }}", "{{ io_name }}\nInvestigating Officer")
    _line(doc, "NOTE: Draft generated by CrimeGPT — to be verified and signed by the officer.")
    doc.save(HERE / "medical_letter.docx")


def main():
    build_seizure_receipt()
    build_panchnama()
    build_remand_request()
    build_medical_letter()
    print("Built templates in", HERE)
    for f in sorted(HERE.glob("*.docx")):
        print("  -", f.name)


if __name__ == "__main__":
    main()
