"""Per-language boilerplate labels for the document templates (CLAUDE.md §8, §4 L10n).

One template serves all three languages: every hardcoded heading / column header /
clause label / salutation / signature label / note lives here, keyed EN / HI / GU, and
the template renders ``{{ L.key }}``. services/documents.py injects ``L = LABELS[lang]``
into the render context.

IDENTIFIERS ARE NEVER IN HERE — case numbers, FIR numbers, person names, section codes,
dates and amounts stay verbatim as their own ``{{ field }}`` merge tags in the template.

A few labels are whole sentences that embed an identifier mid-clause (e.g. the remand's
clause 1 names the accused). Those carry ``{placeholder}`` slots and are assembled with
``str.format`` in _build_context so grammar stays natural per language while the identifier
is substituted verbatim; they are keyed with a trailing ``_S`` (sentence).

Kept import-free (loaded by file path, like _registry.py).

TODO_GU: entries tagged ``# TODO_GU`` are best-effort Gujarati that a native
Gujarati-speaking officer should confirm (chiefly formal legal phrasing). They render as
normal Gujarati (no marker leaks into the .docx); the tag is only here in source.
"""

# --------------------------------------------------------------------------------------
LABELS = {
    # ==================================================================================
    "en": {
        # -- shared --
        "to": "To,",
        "name": "Name",
        "son_of": "S/o",
        "father_name": "Father's name",
        "age": "Age",
        "address": "Address",
        "signature": "Signature",
        "police_station": "Police Station",
        "district": "District",
        "case_fir_no": "Case / FIR No.",
        "fir_no": "FIR No.",
        "fir_date": "FIR Date",
        "date": "Date",
        "place": "Place",
        "io_designation": "Investigating Officer",
        "dated": "dated",
        "note_draft": "NOTE: Draft generated by CrimeGPT — to be verified and signed by the officer.",
        "role_accused": "accused",
        "role_victim": "victim",
        "role_complainant": "complainant",
        "hospital_civil": "Civil Hospital",
        "hospital_govt": "the Government Hospital",
        # -- seizure receipt --
        "heading_seizure": "FORM IF4 — PROPERTY SEIZURE MEMO",
        "subtitle_seizure": "(Crime and Criminal Tracking Network and Systems · Bharatiya Nagarik Suraksha Sanhita, 2023)",
        "year": "Year",
        "crime_case_no": "Crime / Case No.",
        "acts_sections": "Acts and Sections",
        "seizure_datetime_label": "Date and time of seizure",
        "seizure_place_label": "Place of seizure",
        "person_seized_from": "Person from whom property seized:",
        "seized_intro_S": "The property described below was seized by {io_name}, Investigating Officer, in the presence of the two independent panch witnesses named below, and each article was thereafter packed and sealed:",
        "col_sr": "Sr.",
        "col_desc_property": "Description of property",
        "col_qty": "Qty",
        "col_est_value": "Est. value",
        "indep_panch_label": "Independent panch witnesses:",
        "seizing_officer_label": "Seizing / Investigating Officer:",
        "rank": "Rank",
        "buckle_no": "Buckle (Badge) No.",
        # -- panchnama --
        "heading_panchnama": "PANCHNAMA",
        "panch_intro_S": "Before me, {io_name}, Investigating Officer of the above case, the panch witnesses named below were called and the purpose of this panchnama was explained to them. In their presence the following proceedings were carried out:",
        "panch_witnesses_label": "Panch witnesses:",
        "col_no": "No.",
        "accused_label": "Accused:",
        "accused_line_S": "{accused_name}, son of {accused_father}, age {accused_age}, residing at {accused_address}.",
        "col_description": "Description",
        "col_quantity": "Quantity",
        "col_est_value2": "Estimated value",
        "narrative_label": "Narrative of proceedings:",
        "articles_label": "Articles found / seized during the proceedings:",
        "panchnama_closing": "The above panchnama was read over and explained to the panchas, who admitted it to be correct and signed below.",
        "panch_sign_label": "Panch witnesses (sign)",
        # -- remand --
        "remand_court_line2": "The Hon'ble Court of the Learned Judicial Magistrate,",
        "heading_remand": "APPLICATION FOR POLICE CUSTODY REMAND",
        "remand_subtitle": "(Under Section 187 of the Bharatiya Nagarik Suraksha Sanhita, 2023)",
        "respectfully": "Respectfully showeth:",
        "remand_c1_S": "1. That the accused {accused_name}, son of {accused_father}, age {accused_age}, residing at {accused_address}, has been arrested in connection with the above case.",
        "remand_c2": "2. That the following sections of law have been applied in this case:",
        "col_act": "Act",
        "col_section": "Section",
        "col_title": "Title",
        "remand_c3": "3. Investigation carried out so far:",
        "remand_c4": "4. Investigation still pending:",
        "remand_c5": "5. Grounds for seeking police custody:",
        "remand_prayer": "It is therefore prayed that the accused be remanded to police custody to enable completion of the investigation.",
        # -- custody letter (forwarding accused to judicial custody; addressed to the same
        #    Judicial Magistrate as the remand, so it reuses remand_court_line2 /
        #    remand_subtitle (BNSS §187) / remand_c2 / col_* / sig-block labels) --
        "heading_custody": "APPLICATION FOR JUDICIAL CUSTODY REMAND",
        "custody_c1_S": "1. That the accused {accused_name}, son of {accused_father}, age {accused_age}, residing at {accused_address}, has been arrested and is presently in custody in connection with the above case.",
        "custody_c3": "3. That the accused was earlier remanded to police custody, and the period of police custody granted (from ____________ to ____________) has now been completed.",
        "custody_c4": "4. That the investigation is continuing and the presence of the accused is required for the purposes of the investigation and trial; no further police custody of the accused is required at this stage.",
        "custody_prayer": "It is therefore prayed that the accused be remanded to judicial custody and forwarded to the District Jail pending further proceedings.",
        # -- medical --
        "medical_to2": "The Medical Officer,",
        "heading_medical": "REQUEST FOR MEDICAL EXAMINATION",
        "from_label": "From:",
        "sir_madam": "Sir / Madam,",
        "med_body_S": "In connection with the above case, {subject_name} ({subject_role}) is being produced before you. You are requested to conduct the medical examination of the said person for the following purpose:",
        "purpose_label": "Purpose of examination:",
        "med_closing": "You are further requested to furnish the medical examination report and certificate to this office at the earliest for the purpose of investigation.",
        # -- document narrative sentences (moved OUT of the LLM translation path) --
        # These were previously drafted in English in services/documents.py and machine-
        # translated for HI/GU — which mistranslated "seized" as "looted" (લૂટ) in Gujarati
        # and truncated the Hindi mid-word. They are now hand-written per language with
        # {placeholder} slots for identifiers, exactly like the other `_S` sentences.
        "accused_named_above": "named above",
        "panch_narrative_S": "In connection with case {case_number}, the place and the articles connected with the offence were examined in the presence of the panch witnesses. On examination the article(s) described below were found and seized as per law.",
        "remand_inv_fir_S": "The complaint was registered vide FIR No. {fir_number} dated {fir_date} at {police_station}.",
        "remand_inv_arrested_S": "The accused {accused_name} has been arrested.",
        "remand_inv_seized_S": "The following article(s) have been seized during investigation: {item_list}.",
        "remand_inv_stmts_S": "Statement(s) of {statement_count} witness(es)/person(s) have been recorded.",
        "remand_inv_stmts_progress": "Recording of witness statements is in progress.",
        "remand_pending_S": "Recovery of the remaining case property, verification of the antecedents of the accused, identification of any associates, and recording of further statements remain to be completed.",
        "remand_grounds_S": "The custodial interrogation of the accused {accused_name} is necessary to recover the remaining case property, to identify the associates involved in the offence, and to complete the investigation. There is a likelihood of the accused tampering with evidence or influencing witnesses if not taken into custody.",
        "med_purpose_accused_S": "Medical examination of the accused to record the physical condition and any injuries prior to production before the Hon'ble Court.",
        "med_purpose_general_S": "Medical examination and treatment of the person named above and issuance of the medical certificate for the purpose of investigation.",
        # -- LERS (shared + per-type) --
        "lers_compliant_note": "COMPLIANT LAW-ENFORCEMENT REQUEST TEMPLATE — not a live platform API integration.",
        "lers_to": "To: The Law Enforcement Response Team,",
        "lers_platform": "Platform:",
        "lers_agency": "Requesting agency:",
        "lers_io": "Investigating Officer:",
        "lers_badge": "Badge/Buckle No.",
        "lers_legal_basis_a": "Legal basis: Under Section 94 of the Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS) — order to produce a document or other thing,",
        "lers_legal_basis_b": "in connection with an offence under",
        "lers_target": "Target identifier (account ID / phone number / profile URL):",
        "lers_other": "Other:",
        "lers_note": "NOTE: Compliant request template generated by CrimeGPT — to be verified and signed by the officer. This is not a live platform API integration.",
        "lers_pres_heading": "DATA PRESERVATION REQUEST",
        "lers_pres_data": "Data to be PRESERVED (do not disclose at this stage):",
        "lers_opt_subscriber": "Subscriber / registration information",
        "lers_opt_iphist": "Login IP history",
        "lers_opt_metadata": "Message / call metadata",
        "lers_opt_content": "Media and stored content",
        "lers_pres_period": "Period for which data is to be preserved: from ____________ to ____________",
        "lers_pres_statement": "PRESERVATION STATEMENT: Pursuant to a lawful investigation, you are requested to PRESERVE and NOT delete or alter the data described above associated with the identifier(s) above for a period of ninety (90) days, extendable on further request, pending service of formal legal process for its disclosure. This is a preservation request only — no disclosure of data is sought at this stage.",
        "lers_rec_heading": "RECORDS DISCLOSURE REQUEST",
        "lers_rec_data": "Records / data SOUGHT for disclosure:",
        "lers_opt_basic": "Basic subscriber information",
        "lers_opt_iplogs": "Login / IP logs",
        "lers_opt_txn": "Transactional / message metadata",
        "lers_opt_stored": "Stored content (where lawfully permitted)",
        "lers_rec_daterange": "Date range of records requested: from ____________ to ____________",
        "lers_rec_statement": "DISCLOSURE STATEMENT: Pursuant to the legal basis stated above, you are requested to DISCLOSE the records described above for the identifier(s) and period specified, certified as true records, in a machine-readable format, to the requesting officer through the platform's Law Enforcement Response System. Please cite the Case / FIR number above in your response.",
    },
    # ==================================================================================
    "hi": {
        "to": "सेवा में,",
        "name": "नाम",
        "son_of": "पिता",
        "father_name": "पिता का नाम",
        "age": "उम्र",
        "address": "पता",
        "signature": "हस्ताक्षर",
        "police_station": "पुलिस थाना",
        "district": "जिला",
        "case_fir_no": "केस / एफ.आई.आर. नं.",
        "fir_no": "एफ.आई.आर. नं.",
        "fir_date": "एफ.आई.आर. दिनांक",
        "date": "दिनांक",
        "place": "स्थान",
        "io_designation": "अन्वेषण अधिकारी",
        "dated": "दिनांकित",
        "note_draft": "टिप्पणी: यह मसौदा CrimeGPT द्वारा तैयार किया गया है — अधिकारी द्वारा सत्यापित एवं हस्ताक्षरित किया जाना है।",
        "role_accused": "आरोपी",
        "role_victim": "पीड़ित",
        "role_complainant": "शिकायतकर्ता",
        "hospital_civil": "सिविल अस्पताल",
        "hospital_govt": "सरकारी अस्पताल",
        "heading_seizure": "फॉर्म IF4 — संपत्ति जब्ती ज्ञापन",
        "subtitle_seizure": "(क्राइम एंड क्रिमिनल ट्रैकिंग नेटवर्क एंड सिस्टम्स · भारतीय नागरिक सुरक्षा संहिता, 2023)",
        "year": "वर्ष",
        "crime_case_no": "अपराध / केस नं.",
        "acts_sections": "अधिनियम एवं धाराएँ",
        "seizure_datetime_label": "जब्ती की तिथि एवं समय",
        "seizure_place_label": "जब्ती का स्थान",
        "person_seized_from": "जिस व्यक्ति से संपत्ति जब्त की गई:",
        "seized_intro_S": "नीचे वर्णित संपत्ति {io_name}, अन्वेषण अधिकारी, द्वारा नीचे नामित दो स्वतंत्र पंच गवाहों की उपस्थिति में जब्त की गई, और प्रत्येक वस्तु को तत्पश्चात पैक कर सील किया गया:",
        "col_sr": "क्र.",
        "col_desc_property": "संपत्ति का विवरण",
        "col_qty": "मात्रा",
        "col_est_value": "अनु. मूल्य",
        "indep_panch_label": "स्वतंत्र पंच गवाह:",
        "seizing_officer_label": "जब्तकर्ता / अन्वेषण अधिकारी:",
        "rank": "पद",
        "buckle_no": "बक्कल (बैज) नं.",
        "heading_panchnama": "पंचनामा",
        "panch_intro_S": "मेरे समक्ष, {io_name}, उपरोक्त केस के अन्वेषण अधिकारी, ने नीचे नामित पंच गवाहों को बुलाकर इस पंचनामे का उद्देश्य समझाया। उनकी उपस्थिति में निम्नलिखित कार्यवाही की गई:",
        "panch_witnesses_label": "पंच गवाह:",
        "col_no": "क्र.",
        "accused_label": "आरोपी:",
        "accused_line_S": "{accused_name}, पिता {accused_father}, उम्र {accused_age}, निवासी {accused_address}।",
        "col_description": "विवरण",
        "col_quantity": "मात्रा",
        "col_est_value2": "अनुमानित मूल्य",
        "narrative_label": "कार्यवाही का विवरण:",
        "articles_label": "कार्यवाही के दौरान पाई / जब्त की गई वस्तुएँ:",
        "panchnama_closing": "उपरोक्त पंचनामा पंचों को पढ़कर सुनाया एवं समझाया गया, जिसे उन्होंने सही स्वीकार कर नीचे हस्ताक्षर किए।",
        "panch_sign_label": "पंच गवाह (हस्ताक्षर)",
        "remand_court_line2": "माननीय न्यायिक मजिस्ट्रेट महोदय की अदालत में,",
        "heading_remand": "पुलिस कस्टडी रिमांड हेतु आवेदन",
        "remand_subtitle": "(भारतीय नागरिक सुरक्षा संहिता, 2023 की धारा 187 के अंतर्गत)",
        "respectfully": "सविनय निवेदन है:",
        "remand_c1_S": "1. यह कि आरोपी {accused_name}, पिता {accused_father}, उम्र {accused_age}, निवासी {accused_address}, को उपरोक्त केस के संबंध में गिरफ्तार किया गया है।",
        "remand_c2": "2. यह कि इस केस में कानून की निम्नलिखित धाराएँ लागू की गई हैं:",
        "col_act": "अधिनियम",
        "col_section": "धारा",
        "col_title": "शीर्षक",
        "remand_c3": "3. अब तक की गई जाँच:",
        "remand_c4": "4. शेष जाँच:",
        "remand_c5": "5. पुलिस कस्टडी हेतु आधार:",
        "remand_prayer": "अतः प्रार्थना है कि जाँच पूर्ण करने हेतु आरोपी को पुलिस कस्टडी में रिमांड किया जाए।",
        # -- custody letter (hand-written Hindi; formal legal phrasing tagged TODO_HI) --
        "heading_custody": "न्यायिक हिरासत रिमांड हेतु आवेदन",  # TODO_HI: confirm court-form wording
        "custody_c1_S": "1. यह कि आरोपी {accused_name}, पिता {accused_father}, उम्र {accused_age}, निवासी {accused_address}, को उपरोक्त केस के संबंध में गिरफ्तार किया गया है तथा वर्तमान में हिरासत में है।",
        "custody_c3": "3. यह कि आरोपी को पूर्व में पुलिस कस्टडी में रिमांड किया गया था, तथा दी गई पुलिस कस्टडी की अवधि (दिनांक ____________ से ____________ तक) अब पूर्ण हो चुकी है।",  # TODO_HI: confirm legal phrasing
        "custody_c4": "4. यह कि जाँच जारी है तथा जाँच एवं विचारण हेतु आरोपी की उपस्थिति आवश्यक है; इस स्तर पर आरोपी की और पुलिस कस्टडी आवश्यक नहीं है।",  # TODO_HI: confirm legal phrasing
        "custody_prayer": "अतः प्रार्थना है कि आरोपी को न्यायिक हिरासत में रिमांड कर आगे की कार्यवाही हेतु जिला कारागार भेजा जाए।",  # TODO_HI: confirm legal phrasing
        "medical_to2": "चिकित्सा अधिकारी,",
        "heading_medical": "चिकित्सा परीक्षण हेतु अनुरोध",
        "from_label": "प्रेषक:",
        "sir_madam": "महोदय / महोदया,",
        "med_body_S": "उपरोक्त केस के संबंध में, {subject_name} ({subject_role}) को आपके समक्ष प्रस्तुत किया जा रहा है। आपसे अनुरोध है कि उक्त व्यक्ति का निम्नलिखित प्रयोजन हेतु चिकित्सा परीक्षण करें:",
        "purpose_label": "परीक्षण का प्रयोजन:",
        "med_closing": "आपसे यह भी अनुरोध है कि जाँच के प्रयोजन हेतु चिकित्सा परीक्षण रिपोर्ट एवं प्रमाणपत्र शीघ्रातिशीघ्र इस कार्यालय को प्रस्तुत करें।",
        # -- document narrative sentences (hand-written Hindi; see the EN note above). No
        #    reviewed Hindi exists, so the formal-legal phrasing is tagged TODO_HI for a
        #    native-speaker pass; it renders as normal Hindi (no marker leaks into the .docx).
        "accused_named_above": "उपर्युक्त नामित",
        "panch_narrative_S": "उपरोक्त केस {case_number} के संबंध में, अपराध से संबंधित स्थान एवं वस्तुओं का पंच गवाहों की उपस्थिति में निरीक्षण किया गया। निरीक्षण के दौरान नीचे वर्णित वस्तु(एँ) पाई गईं एवं कानून के अनुसार जब्त की गईं।",  # TODO_HI: confirm legal phrasing
        "remand_inv_fir_S": "शिकायत एफ.आई.आर. नं. {fir_number} दिनांक {fir_date} को {police_station} में पंजीकृत की गई।",
        "remand_inv_arrested_S": "आरोपी {accused_name} को गिरफ्तार किया गया है।",
        "remand_inv_seized_S": "जाँच के दौरान निम्नलिखित वस्तु(एँ) जब्त की गई हैं: {item_list}।",
        "remand_inv_stmts_S": "{statement_count} साक्षी/व्यक्ति के बयान दर्ज किए गए हैं।",
        "remand_inv_stmts_progress": "साक्षियों के बयान दर्ज किए जा रहे हैं।",
        "remand_pending_S": "शेष मुद्दामाल की बरामदगी, आरोपी के पूर्ववृत्त का सत्यापन, किसी सहयोगी की पहचान, तथा आगे के बयान दर्ज करना शेष है।",  # TODO_HI: confirm legal phrasing
        "remand_grounds_S": "बाकी मुद्दामाल की बरामदगी हेतु, अपराध में संलिप्त सहयोगियों की पहचान हेतु तथा जाँच पूर्ण करने हेतु आरोपी {accused_name} से हिरासत में पूछताछ आवश्यक है। यदि आरोपी को हिरासत में नहीं लिया गया तो उसके द्वारा साक्ष्य से छेड़छाड़ करने अथवा साक्षियों को प्रभावित करने की संभावना है।",  # TODO_HI: confirm legal phrasing
        "med_purpose_accused_S": "माननीय न्यायालय के समक्ष प्रस्तुत करने से पूर्व आरोपी की शारीरिक स्थिति एवं किसी भी चोट को अभिलिखित करने हेतु आरोपी का चिकित्सा परीक्षण।",  # TODO_HI: confirm legal phrasing
        "med_purpose_general_S": "जाँच के प्रयोजन हेतु उपर्युक्त नामित व्यक्ति का चिकित्सा परीक्षण एवं उपचार तथा चिकित्सा प्रमाणपत्र जारी करना।",  # TODO_HI: confirm legal phrasing
        "lers_compliant_note": "अनुपालनयुक्त विधि-प्रवर्तन अनुरोध टेम्पलेट — यह किसी लाइव प्लेटफ़ॉर्म API एकीकरण नहीं है।",
        "lers_to": "सेवा में: विधि प्रवर्तन प्रतिक्रिया दल,",
        "lers_platform": "प्लेटफ़ॉर्म:",
        "lers_agency": "अनुरोधकर्ता एजेंसी:",
        "lers_io": "अन्वेषण अधिकारी:",
        "lers_badge": "बैज/बक्कल नं.",
        "lers_legal_basis_a": "विधिक आधार: भारतीय नागरिक सुरक्षा संहिता, 2023 (BNSS) की धारा 94 (दस्तावेज़ या अन्य वस्तु प्रस्तुत करने का आदेश) के अंतर्गत,",
        "lers_legal_basis_b": "निम्न अपराध के संबंध में",
        "lers_target": "लक्ष्य पहचानकर्ता (अकाउंट आईडी / फ़ोन नंबर / प्रोफ़ाइल URL):",
        "lers_other": "अन्य:",
        "lers_note": "टिप्पणी: यह अनुपालनयुक्त अनुरोध टेम्पलेट CrimeGPT द्वारा तैयार किया गया है — अधिकारी द्वारा सत्यापित एवं हस्ताक्षरित किया जाना है। यह किसी लाइव प्लेटफ़ॉर्म API एकीकरण नहीं है।",
        "lers_pres_heading": "डेटा संरक्षण अनुरोध",
        "lers_pres_data": "संरक्षित किया जाने वाला डेटा (इस चरण पर प्रकट न करें):",
        "lers_opt_subscriber": "सब्सक्राइबर / पंजीकरण जानकारी",
        "lers_opt_iphist": "लॉगिन IP इतिहास",
        "lers_opt_metadata": "संदेश / कॉल मेटाडेटा",
        "lers_opt_content": "मीडिया एवं संग्रहीत सामग्री",
        "lers_pres_period": "जिस अवधि हेतु डेटा संरक्षित किया जाना है: ____________ से ____________ तक",
        "lers_pres_statement": "संरक्षण कथन: विधिसम्मत जाँच के अनुसरण में, आपसे अनुरोध है कि उपरोक्त पहचानकर्ता से संबद्ध उपरोक्त वर्णित डेटा को नब्बे (90) दिनों की अवधि हेतु संरक्षित रखें एवं न तो हटाएँ न परिवर्तित करें, जो आगे के अनुरोध पर विस्तारणीय है, तथा उसके प्रकटीकरण हेतु औपचारिक विधिक प्रक्रिया की तामील तक लंबित रहेगा। यह केवल एक संरक्षण अनुरोध है — इस चरण पर डेटा का कोई प्रकटीकरण नहीं माँगा गया है।",
        "lers_rec_heading": "रिकॉर्ड प्रकटीकरण अनुरोध",
        "lers_rec_data": "प्रकटीकरण हेतु माँगे गए रिकॉर्ड / डेटा:",
        "lers_opt_basic": "मूल सब्सक्राइबर जानकारी",
        "lers_opt_iplogs": "लॉगिन / IP लॉग",
        "lers_opt_txn": "लेन-देन / संदेश मेटाडेटा",
        "lers_opt_stored": "संग्रहीत सामग्री (जहाँ विधिसम्मत रूप से अनुमेय हो)",
        "lers_rec_daterange": "माँगे गए रिकॉर्ड की तिथि सीमा: ____________ से ____________ तक",
        "lers_rec_statement": "प्रकटीकरण कथन: उपरोक्त विधिक आधार के अनुसरण में, आपसे अनुरोध है कि निर्दिष्ट पहचानकर्ता एवं अवधि हेतु उपरोक्त वर्णित रिकॉर्ड को सही रिकॉर्ड के रूप में प्रमाणित करते हुए, मशीन-पठनीय प्रारूप में, प्लेटफ़ॉर्म की विधि प्रवर्तन प्रतिक्रिया प्रणाली के माध्यम से अनुरोधकर्ता अधिकारी को प्रकट करें। कृपया अपनी प्रतिक्रिया में उपरोक्त केस / एफ.आई.आर. संख्या का उल्लेख करें।",
    },
    # ==================================================================================
    "gu": {
        "to": "પ્રતિ,",
        "name": "નામ",
        "son_of": "પિતાનું નામ",
        "father_name": "પિતાનું નામ",
        "age": "ઉંમર",
        "address": "સરનામું",
        "signature": "સહી",
        "police_station": "પોલીસ સ્ટેશન",
        "district": "જિલ્લો",
        "case_fir_no": "કેસ / એફ.આઈ.આર. નં.",
        "fir_no": "એફ.આઈ.આર. નં.",
        "fir_date": "એફ.આઈ.આર. તારીખ",
        "date": "તારીખ",
        "place": "સ્થળ",
        "io_designation": "તપાસ અધિકારી",
        "dated": "તારીખના રોજ",
        "note_draft": "નોંધ: આ મુસદ્દો CrimeGPT દ્વારા તૈયાર કરવામાં આવ્યો છે — અધિકારી દ્વારા ચકાસીને સહી કરવાની રહેશે.",
        "role_accused": "આરોપી",
        "role_victim": "ભોગ બનનાર",
        "role_complainant": "ફરિયાદી",
        "hospital_civil": "સિવિલ હોસ્પિટલ",
        "hospital_govt": "સરકારી હોસ્પિટલ",
        "heading_seizure": "ફોર્મ IF4 — મિલકત જપ્તી મેમો",  # TODO_GU: "મેમો" vs "પંચનામું" — confirm CCTNS-form wording
        "subtitle_seizure": "(ક્રાઈમ એન્ડ ક્રિમિનલ ટ્રેકિંગ નેટવર્ક એન્ડ સિસ્ટમ્સ · ભારતીય નાગરિક સુરક્ષા સંહિતા, 2023)",
        "year": "વર્ષ",
        "crime_case_no": "ગુનો / કેસ નં.",
        "acts_sections": "કાયદા અને કલમો",
        "seizure_datetime_label": "જપ્તીની તારીખ અને સમય",
        "seizure_place_label": "જપ્તીનું સ્થળ",
        "person_seized_from": "જેની પાસેથી મિલકત જપ્ત કરી તે વ્યક્તિ:",
        "seized_intro_S": "નીચે વર્ણવેલ મિલકત {io_name}, તપાસ અધિકારી, દ્વારા નીચે જણાવેલ બે સ્વતંત્ર પંચ સાક્ષીઓની હાજરીમાં જપ્ત કરવામાં આવેલ છે, અને દરેક વસ્તુ ત્યારબાદ પેક કરી સીલ કરવામાં આવેલ છે:",
        "col_sr": "ક્રમ",
        "col_desc_property": "મિલકતનું વર્ણન",
        "col_qty": "જથ્થો",
        "col_est_value": "અંદાજિત કિંમત",
        "indep_panch_label": "સ્વતંત્ર પંચ સાક્ષીઓ:",
        "seizing_officer_label": "જપ્ત કરનાર / તપાસ અધિકારી:",
        "rank": "હોદ્દો",
        "buckle_no": "બકલ (બેજ) નં.",
        "heading_panchnama": "પંચનામું",
        "panch_intro_S": "મારી સમક્ષ, {io_name}, ઉપરોક્ત કેસના તપાસ અધિકારી, દ્વારા નીચે જણાવેલ પંચ સાક્ષીઓને બોલાવીને આ પંચનામાનો હેતુ સમજાવવામાં આવ્યો. તેમની હાજરીમાં નીચે મુજબની કાર્યવાહી કરવામાં આવી:",
        "panch_witnesses_label": "પંચ સાક્ષીઓ:",
        "col_no": "ક્રમ",
        "accused_label": "આરોપી:",
        "accused_line_S": "{accused_name}, પિતાનું નામ {accused_father}, ઉંમર {accused_age}, રહેઠાણ {accused_address}.",
        "col_description": "વર્ણન",
        "col_quantity": "જથ્થો",
        "col_est_value2": "અંદાજિત કિંમત",
        "narrative_label": "કાર્યવાહીની વિગત:",
        "articles_label": "કાર્યવાહી દરમિયાન મળી આવેલ / જપ્ત કરેલ વસ્તુઓ:",
        "panchnama_closing": "ઉપરોક્ત પંચનામું પંચોને વાંચી સંભળાવી સમજાવવામાં આવ્યું, જે તેમણે સાચું સ્વીકારીને નીચે સહી કરી.",
        "panch_sign_label": "પંચ સાક્ષીઓ (સહી)",
        "remand_court_line2": "નામદાર ન્યાયિક મેજિસ્ટ્રેટ સાહેબની અદાલતમાં,",  # TODO_GU: confirm honorific/court form
        "heading_remand": "પોલીસ કસ્ટડી રિમાન્ડ માટેની અરજી",
        "remand_subtitle": "(ભારતીય નાગરિક સુરક્ષા સંહિતા, 2023 ની કલમ 187 હેઠળ)",
        "respectfully": "સવિનય રજૂઆત છે કે:",  # TODO_GU: formal petition opener
        "remand_c1_S": "1. કે આરોપી {accused_name}, પિતાનું નામ {accused_father}, ઉંમર {accused_age}, રહેઠાણ {accused_address}, ની ઉપરોક્ત કેસના સંદર્ભમાં ધરપકડ કરવામાં આવેલ છે.",
        "remand_c2": "2. કે આ કેસમાં કાયદાની નીચે મુજબની કલમો લાગુ કરવામાં આવી છે:",
        "col_act": "કાયદો",
        "col_section": "કલમ",
        "col_title": "શીર્ષક",
        "remand_c3": "3. અત્યાર સુધી કરેલ તપાસ:",
        "remand_c4": "4. બાકી રહેલ તપાસ:",
        "remand_c5": "5. પોલીસ કસ્ટડી માંગવાનાં કારણો:",
        "remand_prayer": "આથી પ્રાર્થના છે કે તપાસ પૂર્ણ કરવા માટે આરોપીને પોલીસ કસ્ટડીમાં રિમાન્ડ આપવામાં આવે.",
        # -- custody letter (hand-written Gujarati; formal legal phrasing tagged TODO_GU) --
        "heading_custody": "ન્યાયિક કસ્ટડી રિમાન્ડ માટેની અરજી",  # TODO_GU: confirm court-form wording
        "custody_c1_S": "1. કે આરોપી {accused_name}, પિતાનું નામ {accused_father}, ઉંમર {accused_age}, રહેઠાણ {accused_address}, ને ઉપરોક્ત કેસના સંદર્ભમાં ધરપકડ કરવામાં આવેલ છે અને હાલમાં કસ્ટડીમાં છે.",
        "custody_c3": "3. કે આરોપીને અગાઉ પોલીસ કસ્ટડીમાં રિમાન્ડ આપવામાં આવેલ હતો, અને આપવામાં આવેલ પોલીસ કસ્ટડીની મુદત (તારીખ ____________ થી ____________ સુધી) હવે પૂર્ણ થઈ ગઈ છે.",  # TODO_GU: confirm legal phrasing
        "custody_c4": "4. કે તપાસ ચાલુ છે અને તપાસ તથા વિચારણ માટે આરોપીની હાજરી જરૂરી છે; આ તબક્કે આરોપીની વધુ પોલીસ કસ્ટડી જરૂરી નથી.",  # TODO_GU: confirm legal phrasing
        "custody_prayer": "આથી પ્રાર્થના છે કે આરોપીને ન્યાયિક કસ્ટડીમાં રિમાન્ડ કરી આગળની કાર્યવાહી માટે જિલ્લા જેલમાં મોકલવામાં આવે.",  # TODO_GU: confirm legal phrasing
        "medical_to2": "તબીબી અધિકારી,",
        "heading_medical": "તબીબી તપાસ માટેની વિનંતી",
        "from_label": "તરફથી:",
        "sir_madam": "સાહેબ / મેડમ,",
        "med_body_S": "ઉપરોક્ત કેસના સંદર્ભમાં, {subject_name} ({subject_role}) ને આપની સમક્ષ રજૂ કરવામાં આવે છે. આપને વિનંતી છે કે ઉક્ત વ્યક્તિની નીચેના હેતુ માટે તબીબી તપાસ કરાવો:",
        "purpose_label": "તપાસનો હેતુ:",
        "med_closing": "આપને વધુમાં વિનંતી છે કે તપાસના હેતુ માટે તબીબી તપાસ અહેવાલ અને પ્રમાણપત્ર વહેલી તકે આ કચેરીને મોકલી આપો.",
        # -- document narrative sentences (GU). Strings marked "reviewed_gu" are the human-
        #    corrected text from demo_cache/reviewed_gu.json, templatized by swapping the
        #    baked-in identifier for a {placeholder}; the rest are hand-written and tagged
        #    TODO_GU for a native-speaker pass. All say "જપ્ત" (seized), never "લૂટ" (looted).
        "accused_named_above": "ઉપર જણાવેલ",  # TODO_GU: confirm
        # reviewed_gu (1_PANCHNAMA_gu.proceedings_narrative), {case_number} templatized:
        "panch_narrative_S": "કેસ નં. {case_number} ના સંદર્ભમાં, ગુના સાથે સંબંધિત સ્થળ તથા વસ્તુઓની પંચ સાક્ષીઓની હાજરીમાં તપાસ કરવામાં આવી હતી. તપાસ દરમિયાન નીચે વર્ણવેલ વસ્તુ(ઓ) મળી આવી હતી અને કાયદા મુજબ જપ્ત કરવામાં આવી હતી.",
        # remand_inv_* split out of reviewed_gu (1_REMAND_gu.investigation_done):
        "remand_inv_fir_S": "{police_station} ખાતે તારીખ {fir_date} ના રોજ ફરિયાદ એફ.આઈ.આર. નં. {fir_number} થી નોંધવામાં આવી હતી.",  # TODO_GU: confirm split grammar
        "remand_inv_arrested_S": "આરોપી {accused_name} ની ધરપકડ કરવામાં આવી છે.",  # TODO_GU: genitive when name is Latin-script
        "remand_inv_seized_S": "તપાસ દરમિયાન નીચે મુજબની વસ્તુ(ઓ) જપ્ત કરવામાં આવી છે: {item_list}.",  # reviewed_gu wording (જપ્ત = seized)
        "remand_inv_stmts_S": "{statement_count} સાક્ષી/ઈસમનાં નિવેદન નોંધવામાં આવ્યાં છે.",  # TODO_GU: confirm split grammar
        "remand_inv_stmts_progress": "સાક્ષીઓનાં નિવેદન નોંધવાની કાર્યવાહી ચાલુ છે.",  # TODO_GU: new (no reviewed source)
        # reviewed_gu (1_REMAND_gu.pending_investigation) verbatim (no identifiers):
        "remand_pending_S": "બાકીના મુદ્દામાલની વસૂલાત, આરોપીના પૂર્વ ઇતિહાસની ચકાસણી, સાથીદારોની ઓળખ તથા વધુ નિવેદનો નોંધવાનું કામ બાકી છે.",
        # reviewed_gu (1_REMAND_gu.grounds_for_custody), {accused_name} templatized:
        "remand_grounds_S": "બાકીના મુદ્દામાલની વસૂલાત કરવા, ગુનામાં સંડોવાયેલા સાથીદારોની ઓળખ કરવા તથા તપાસ પૂર્ણ કરવા માટે આરોપી {accused_name} ની પોલીસ કસ્ટડીમાં પૂછપરછ કરવી જરૂરી છે. જો આરોપીને કસ્ટડીમાં લેવામાં નહીં આવે તો તે પુરાવા સાથે ચેડાં કરે અથવા સાક્ષીઓને પ્રભાવિત કરે તેવી શક્યતા છે.",
        # reviewed_gu (1_MEDICAL_LETTER_gu.examination_purpose) verbatim:
        "med_purpose_accused_S": "નામદાર અદાલત સમક્ષ રજૂ કરતાં પહેલાં આરોપીની શારીરિક સ્થિતિ તથા ઈજાઓની નોંધ કરવા માટે તબીબી તપાસ કરાવવા બાબત.",
        "med_purpose_general_S": "તપાસના હેતુ માટે ઉપર જણાવેલ વ્યક્તિની તબીબી તપાસ તથા સારવાર અને તબીબી પ્રમાણપત્ર આપવા બાબત.",  # TODO_GU: new (no reviewed source)
        "lers_compliant_note": "સુસંગત કાયદા-અમલીકરણ વિનંતી ટેમ્પલેટ — આ કોઈ જીવંત પ્લેટફોર્મ API સંકલન નથી.",  # TODO_GU: technical phrasing
        "lers_to": "પ્રતિ: લો એન્ફોર્સમેન્ટ રિસ્પોન્સ ટીમ,",
        "lers_platform": "પ્લેટફોર્મ:",
        "lers_agency": "વિનંતી કરનાર એજન્સી:",
        "lers_io": "તપાસ અધિકારી:",
        "lers_badge": "બેજ/બકલ નં.",
        "lers_legal_basis_a": "કાયદાકીય આધાર: ભારતીય નાગરિક સુરક્ષા સંહિતા, 2023 (BNSS) ની કલમ 94 (દસ્તાવેજ કે અન્ય વસ્તુ રજૂ કરવાનો આદેશ) હેઠળ,",
        "lers_legal_basis_b": "નીચેના ગુનાના સંદર્ભમાં",
        "lers_target": "લક્ષ્ય ઓળખકર્તા (એકાઉન્ટ આઈડી / ફોન નંબર / પ્રોફાઇલ URL):",
        "lers_other": "અન્ય:",
        "lers_note": "નોંધ: આ સુસંગત વિનંતી ટેમ્પલેટ CrimeGPT દ્વારા તૈયાર કરવામાં આવ્યું છે — અધિકારી દ્વારા ચકાસીને સહી કરવાની રહેશે. આ કોઈ જીવંત પ્લેટફોર્મ API સંકલન નથી.",
        "lers_pres_heading": "ડેટા જાળવણી વિનંતી",
        "lers_pres_data": "જાળવવાનો ડેટા (આ તબક્કે જાહેર ન કરવો):",
        "lers_opt_subscriber": "સબ્સ્ક્રાઇબર / નોંધણી માહિતી",
        "lers_opt_iphist": "લોગિન IP ઇતિહાસ",
        "lers_opt_metadata": "સંદેશ / કૉલ મેટાડેટા",
        "lers_opt_content": "મીડિયા અને સંગ્રહિત સામગ્રી",
        "lers_pres_period": "જે સમયગાળા માટે ડેટા જાળવવાનો છે: ____________ થી ____________ સુધી",
        "lers_pres_statement": "જાળવણી નિવેદન: કાયદેસરની તપાસના અનુસંધાનમાં, આપને વિનંતી છે કે ઉપરોક્ત ઓળખકર્તા સાથે સંકળાયેલ ઉપર વર્ણવેલ ડેટા નેવું (90) દિવસના સમયગાળા માટે જાળવી રાખો અને ન તો કાઢી નાખો કે ન બદલો, જે વધુ વિનંતી પર લંબાવી શકાય છે, અને તેની જાહેરાત માટે ઔપચારિક કાયદાકીય પ્રક્રિયાની બજવણી સુધી બાકી રહેશે. આ માત્ર જાળવણી વિનંતી છે — આ તબક્કે ડેટાની કોઈ જાહેરાત માંગવામાં આવી નથી.",  # TODO_GU: long legal statement — confirm
        "lers_rec_heading": "રેકોર્ડ જાહેરાત વિનંતી",
        "lers_rec_data": "જાહેરાત માટે માંગેલ રેકોર્ડ / ડેટા:",
        "lers_opt_basic": "મૂળભૂત સબ્સ્ક્રાઇબર માહિતી",
        "lers_opt_iplogs": "લોગિન / IP લોગ",
        "lers_opt_txn": "વ્યવહાર / સંદેશ મેટાડેટા",
        "lers_opt_stored": "સંગ્રહિત સામગ્રી (જ્યાં કાયદેસર રીતે માન્ય હોય)",
        "lers_rec_daterange": "માંગેલ રેકોર્ડની તારીખ મર્યાદા: ____________ થી ____________ સુધી",
        "lers_rec_statement": "જાહેરાત નિવેદન: ઉપરોક્ત કાયદાકીય આધારના અનુસંધાનમાં, આપને વિનંતી છે કે નિર્દિષ્ટ ઓળખકર્તા અને સમયગાળા માટે ઉપર વર્ણવેલ રેકોર્ડ સાચા રેકોર્ડ તરીકે પ્રમાણિત કરીને, મશીન-વાંચનીય ફોર્મેટમાં, પ્લેટફોર્મની લો એન્ફોર્સમેન્ટ રિસ્પોન્સ સિસ્ટમ મારફતે વિનંતી કરનાર અધિકારીને જાહેર કરો. કૃપા કરીને આપના જવાબમાં ઉપરોક્ત કેસ / એફ.આઈ.આર. નંબરનો ઉલ્લેખ કરો.",  # TODO_GU: long legal statement — confirm
    },
}


def get_labels(lang: str) -> dict:
    """Return the label dict for a language code (gu|hi|en), falling back to English."""
    return LABELS.get((lang or "en").lower(), LABELS["en"])
